#!/usr/bin/env python3
"""
Test: Verify that bin/agent-city launcher actually loads all agents into kernel.

This test ensures the kernel is NOT empty—that all 5 cartridges are:
1. Imported
2. Instantiated
3. Registered with kernel
4. Loaded before any snapshot/status is generated
"""

import json
import logging
import sys
from pathlib import Path

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("TEST_LAUNCHER_AGENTS")


def test_launcher_kernel_boot():
    """Test: Boot kernel via launcher code path and verify agents are loaded."""
    logger.info("\n" + "=" * 70)
    logger.info("TEST: Launcher Kernel Boot with Agent Loading")
    logger.info("=" * 70)

    project_root = Path(__file__).parent
    sys.path.insert(0, str(project_root))

    try:
        # Simulate what bin/agent-city does in boot_kernel()
        from vibe_core.kernel_impl import RealVibeKernel
        from herald.cartridge_main import HeraldCartridge
        from civic.cartridge_main import CivicCartridge
        from forum.cartridge_main import ForumCartridge
        from science.cartridge_main import ScientistCartridge
        from envoy.cartridge_main import EnvoyCartridge

        logger.info("✅ All imports successful")

        # Create kernel (same as launcher)
        kernel = RealVibeKernel()
        logger.info("✅ Kernel instance created")

        # Register agents (same as launcher)
        agents_to_register = [
            ("herald", HeraldCartridge()),
            ("civic", CivicCartridge()),
            ("forum", ForumCartridge()),
            ("science", ScientistCartridge()),
            ("envoy", EnvoyCartridge()),
        ]

        for agent_id, agent_instance in agents_to_register:
            kernel.register_agent(agent_instance)
            logger.info(f"✅ Agent registered: {agent_id}")

        # Boot kernel
        kernel.boot()
        logger.info("✅ Kernel booted")

        # Verify agents are registered
        status = kernel.get_status()
        agents_count = status.get("agents_registered", 0)
        manifests_count = status.get("manifests", 0)

        logger.info(f"\n📊 Kernel Status:")
        logger.info(f"   Agents Registered: {agents_count}")
        logger.info(f"   Manifests Loaded: {manifests_count}")

        # CRITICAL: Check that we have 5 agents, not 0
        assert agents_count == 5, f"Expected 5 agents, got {agents_count} (EMPTY KERNEL)"
        assert manifests_count == 5, f"Expected 5 manifests, got {manifests_count}"

        logger.info("\n✅ KERNEL IS NOT EMPTY - All agents loaded!")

        # Verify each agent is in registry
        registry_keys = list(kernel.agent_registry.keys())
        logger.info(f"\n🤖 Registered agents: {', '.join(registry_keys)}")

        expected_agents = {"herald", "civic", "forum", "science", "envoy"}
        actual_agents = set(registry_keys)

        assert actual_agents == expected_agents, f"Expected {expected_agents}, got {actual_agents}"

        logger.info("✅ All expected agents present in registry")

        return True

    except Exception as e:
        logger.error(f"❌ Test failed: {e}")
        import traceback
        traceback.print_exc()
        return False


def test_snapshot_has_agents():
    """Test: Verify vibe_snapshot.json contains all 5 agents with RUNNING status."""
    logger.info("\n" + "=" * 70)
    logger.info("TEST: Snapshot Contains All Agents")
    logger.info("=" * 70)

    try:
        snapshot_path = Path(__file__).parent / ".steward" / "vibe_snapshot.json"

        if not snapshot_path.exists():
            logger.warning(f"⚠️  Snapshot not found at {snapshot_path}")
            logger.info("   (Snapshot will be generated by --snapshot flag)")
            return True

        with open(snapshot_path) as f:
            snapshot = json.load(f)

        agents = snapshot.get("agents", {})
        agent_count = len(agents)
        agent_ids = list(agents.keys())

        logger.info(f"\n📸 Snapshot Agents: {agent_count}")
        logger.info(f"   IDs: {', '.join(agent_ids)}")

        # CRITICAL: Check that we have 5 agents
        assert agent_count == 5, f"Expected 5 agents in snapshot, got {agent_count} (EMPTY SNAPSHOT)"

        expected_agents = {"herald", "civic", "forum", "science", "envoy"}
        actual_agents = set(agent_ids)
        assert actual_agents == expected_agents, f"Expected {expected_agents}, got {actual_agents}"

        # Check all agents are RUNNING
        logger.info(f"\n✅ Agent Statuses:")
        for agent_id, agent_data in agents.items():
            status = agent_data.get("status", "UNKNOWN")
            logger.info(f"   {agent_id}: {status}")
            assert status == "RUNNING", f"Agent {agent_id} is {status}, not RUNNING"

        logger.info("\n✅ SNAPSHOT IS NOT EMPTY - All agents RUNNING!")
        return True

    except Exception as e:
        logger.error(f"❌ Test failed: {e}")
        import traceback
        traceback.print_exc()
        return False


def main():
    """Run all tests."""
    logger.info("\n" + "🧪" * 35)
    logger.info("LAUNCHER AGENT LOADING TEST SUITE")
    logger.info("🧪" * 35)

    results = {
        "Kernel Boot with Agent Loading": test_launcher_kernel_boot(),
        "Snapshot Contains All Agents": test_snapshot_has_agents(),
    }

    # Summary
    logger.info("\n" + "=" * 70)
    logger.info("TEST SUMMARY")
    logger.info("=" * 70)

    passed = sum(1 for v in results.values() if v)
    total = len(results)

    for test_name, result in results.items():
        status = "✅ PASS" if result else "❌ FAIL"
        logger.info(f"{status}: {test_name}")

    logger.info(f"\nTotal: {passed}/{total} tests passed")

    if passed == total:
        logger.info("\n🎉 ALL TESTS PASSED! Launcher loads agents correctly.")
        return 0
    else:
        logger.error(f"\n❌ {total - passed} test(s) failed.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
