"""
THE ARTISAN - Media & Tech Ops Agent.
Part of the Steward Protocol Federation.

Role: Handyman / Blacksmith
Mission: Polish, Format, and Brand assets generated by HERALD.
"""

import logging
import sys
from typing import Dict, Any

# VibeOS Integration
from vibe_core import VibeAgent, Task

from .tools.media_tool import MediaTool

# Constitutional Oath
# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("ARTISAN_AGENT")


class ArtisanCartridge(VibeAgent):
    """
    The Artisan Agent Cartridge.
    Specialized in media processing and technical operations.
    """

    def __init__(self):
        """Initialize the Artisan as a VibeAgent."""
        # Initialize VibeAgent base class
        super().__init__(
            agent_id="artisan",
            name="ARTISAN",
            version="1.0.0",
            author="Steward Protocol",
            description="Media and technical operations agent",
            domain="MEDIA_OPS",
            capabilities=["media_processing", "image_optimization", "asset_branding"]
        )

        logger.info("🔨 THE ARTISAN is online.")

        # Initialize Constitutional Oath mixin (if available)
        if OathMixin:
            self.oath_mixin_init(self.agent_id)
            # SWEAR THE OATH IMMEDIATELY in __init__
            self.oath_sworn = True
            logger.info("✅ ARTISAN has sworn the Constitutional Oath")

        self.media_tool = MediaTool()

    def process_media(self, file_path: str) -> str:
        """
        Process a media file (Crop, Brand, Optimize).
        
        Args:
            file_path: Path to raw media file
            
        Returns:
            str: Path to processed file (or original if failed)
        """
        logger.info(f"🔨 Artisan received job: Process {file_path}")
        
        processed_path = self.media_tool.process_image(file_path)
        
        if processed_path:
            logger.info(f"✅ Artisan finished job: {processed_path}")
            return processed_path
        else:
            logger.warning("⚠️  Artisan could not process file, returning original.")
            return file_path

    # ==================== VIBEOS AGENT INTERFACE ====================

    def process(self, task: Task) -> Dict[str, Any]:
        """
        Process a task from the VibeKernel scheduler.

        ARTISAN responds to media processing tasks:
        - "process_media": Process a media file
        """
        try:
            action = task.payload.get("action") or task.payload.get("command")
            logger.info(f"🔨 ARTISAN processing task: {action}")

            if action == "process_media":
                file_path = task.payload.get("file_path")
                if not file_path:
                    return {"status": "error", "error": "file_path required"}
                result = self.process_media(file_path)
                return {"status": "success", "result": result}
            else:
                return {
                    "status": "error",
                    "error": f"Unknown action: {action}"
                }
        except Exception as e:
            logger.error(f"❌ ARTISAN processing error: {e}")
            import traceback
            logger.error(traceback.format_exc())
            return {
                "status": "error",
                "error": str(e)
            }
    def get_manifest(self):
        """Return agent manifest for kernel registry."""
        from vibe_core.agent_protocol import AgentManifest
        return AgentManifest(
            agent_id="artisan",
            name="ARTISAN",
            version=self.version if hasattr(self, 'version') else "1.0.0",
            domain="MEDIA",
            capabilities=['media_operations', 'content_creation']
        )



    def report_status(self) -> Dict[str, Any]:
        """Report ARTISAN status (VibeAgent interface)."""
        return {
            "agent_id": "artisan",
            "name": "ARTISAN",
            "status": "RUNNING",
            "domain": "MEDIA_OPS",
            "capabilities": self.capabilities,
            "description": "Media and technical operations agent"
        }
