#!/usr/bin/env python3
"""
Generate Director's Monitor Dashboard for GitHub STEP_SUMMARY.

Reads dist/content.json and outputs markdown for the approval gate dashboard.
"""

import json
import os


def main():
    """Generate markdown dashboard from content.json."""
    try:
        with open('dist/content.json', 'r') as f:
            data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print(f"Error reading content.json: {e}")
        return

    # Build the summary markdown
    lines = []
    lines.append("**Tweet Text:**")
    lines.append(f"> {data.get('text', 'N/A')}")
    lines.append("")

    # Check for image
    image_file = data.get('image_filename', None)
    if image_file and os.path.exists(f"dist/{image_file}"):
        lines.append(f"**Visual Attachment:** `{image_file}` ✅")
    else:
        lines.append("**Visual Attachment:** None (text-only campaign)")

    lines.append("")
    lines.append("### 🧬 Content Provenance")
    lines.append("- **Generated by:** Brain + Artist Pipeline")
    lines.append("- **Health Check:** ✅ Passed (all dependencies verified)")
    lines.append("- **Editor Review:** ✅ Passed (Senior Editor)")
    lines.append("- **Vibe Alignment:** ✅ Passed (Aligner verified)")

    # Output to stdout (will be appended to GITHUB_STEP_SUMMARY)
    print('\n'.join(lines))


if __name__ == "__main__":
    main()
