"""
LEADERBOARD GENERATOR.

Orchestrates the Agent City Gamification Layer.
1. Loads Pokedex
2. Calculates XP (Referee)
3. Mints Cards (Artisan)
4. Publishes HTML
"""

import json
import logging
from pathlib import Path
from datetime import datetime

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("LEADERBOARD")

from steward.game.referee import Referee
from steward.game.card_generator import CardGenerator

def main():
    logger.info("🎮 Starting Agent City Game Loop...")
    
    # Paths
    pokedex_path = Path("data/federation/pokedex.json")
    docs_dir = Path("docs")
    
    # Initialize components
    referee = Referee()
    artisan = CardGenerator(output_dir=docs_dir / "cards")
    
    # Load Agents
    if not pokedex_path.exists():
        logger.error("❌ Pokedex not found!")
        return
        
    with open(pokedex_path) as f:
        agents = json.load(f)
        
    logger.info(f"👥 Found {len(agents)} agents in Pokedex.")
    
    # Calculate Stats & Mint Cards
    leaderboard = []
    
    for agent in agents:
        agent_id = agent.get("agent_id")
        
        # 1. Calculate XP
        xp = referee.calculate_xp(agent_id)
        tier_info = referee.get_tier(xp)
        
        agent["xp"] = xp
        agent["tier"] = tier_info["name"]
        agent["tier_color"] = tier_info["color"]
        
        # 2. Mint Card
        card_path = artisan.generate_card(agent, tier_info)
        agent["card_path"] = f"cards/{Path(card_path).name}"
        
        leaderboard.append(agent)
        
    # Sort by XP (Desc)
    leaderboard.sort(key=lambda x: x["xp"], reverse=True)
    
    # Generate HTML
    _generate_html(leaderboard, docs_dir / "leaderboard.html")
    logger.info("✅ Leaderboard published to docs/leaderboard.html")

def _generate_html(agents: list, output_path: Path):
    """Generate the HTML leaderboard."""
    
    cards_html = ""
    for i, agent in enumerate(agents):
        rank = i + 1
        cards_html += f"""
        <div class="agent-card" style="border-color: {agent['tier_color']}">
            <div class="rank">#{rank}</div>
            <img src="{agent['card_path']}" alt="{agent['agent_id']} Card">
            <div class="stats">
                <h3>{agent['agent_id']}</h3>
                <p class="role">{agent['role']}</p>
                <p class="xp" style="color: {agent['tier_color']}">{agent['xp']} XP</p>
            </div>
        </div>
        """
        
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Agent City Leaderboard</title>
        <style>
            body {{
                background-color: #0f0f12;
                color: #e0e0e0;
                font-family: 'Courier New', monospace;
                text-align: center;
                padding: 20px;
            }}
            h1 {{
                color: #00ff41;
                text-shadow: 0 0 10px #00ff41;
                margin-bottom: 40px;
            }}
            .grid {{
                display: flex;
                flex-wrap: wrap;
                justify_content: center;
                gap: 30px;
                max-width: 1200px;
                margin: 0 auto;
            }}
            .agent-card {{
                background: #1a1a20;
                border: 2px solid #333;
                border-radius: 10px;
                padding: 10px;
                width: 300px;
                transition: transform 0.2s;
            }}
            .agent-card:hover {{
                transform: scale(1.05);
                box-shadow: 0 0 20px rgba(0, 255, 65, 0.2);
            }}
            .rank {{
                font-size: 2em;
                font-weight: bold;
                color: #555;
                text-align: left;
                padding-left: 10px;
            }}
            img {{
                width: 100%;
                border-radius: 5px;
            }}
            .stats {{
                padding: 10px;
                text-align: left;
            }}
            .role {{
                color: #888;
                font-size: 0.9em;
            }}
            .xp {{
                font-weight: bold;
                font-size: 1.2em;
            }}
            footer {{
                margin-top: 50px;
                color: #555;
                font-size: 0.8em;
            }}
        </style>
    </head>
    <body>
        <h1>👾 AGENT CITY LEADERBOARD 👑</h1>
        <p>The top governed agents of the Steward Federation.</p>
        
        <div class="grid">
            {cards_html}
        </div>
        
        <footer>
            Generated by HERALD v5.0 | {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
        </footer>
    </body>
    </html>
    """
    
    with open(output_path, "w") as f:
        f.write(html)

if __name__ == "__main__":
    main()
