#!/usr/bin/env python3
"""
SCRIBE Agents Renderer - Generate AGENTS.md
"""

from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Any
from .introspector import CartridgeIntrospector


class AgentsRenderer:
    """Render AGENTS.md from cartridge metadata."""

    def __init__(self, root_dir: str = "."):
        self.root_dir = Path(root_dir)
        self.introspector = CartridgeIntrospector(root_dir)
        self.agents = {}

    def scan_and_render(self) -> str:
        """Scan cartridges and render AGENTS.md."""
        # Discover all agents
        self.agents = self.introspector.scan_all(self.root_dir / "steward" / "system_agents")

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        content = f"""# 🏙️ AGENT CITY REGISTRY

**Autogenerated by CIVIC (The Bureaucrat) via Registry Tool**
**Last Updated:** {timestamp}

---

## 🏛️ GOVERNANCE

| Field | Value |
|-------|-------|
| **Constitution** | [CONSTITUTION.md](./CONSTITUTION.md) |
| **Protocol Level** | 3 (Federated Discovery) |
| **Status** | ✅ Active & Enforced |
| **Registry Version** | 2.0 (CIVIC-managed) |
| **Authority** | CIVIC Cartridge |

---

## 🤖 ACTIVE AGENTS

"""

        # Add agent sections
        for agent in sorted(self.agents.values(), key=lambda a: a['agent_name_pretty']):
            content += self._format_agent_section(agent)

        # System summary
        total_tools = sum(len(a['tools']) for a in self.agents.values())
        content += f"""---

## 📊 SYSTEM SUMMARY

| Metric | Value |
|--------|-------|
| **Total Agents** | {len(self.agents)} |
| **Total Tools** | {total_tools} |
| **System Status** | 🟢 All Systems Operational |
| **Registry Authority** | 🏛️ CIVIC (Immutable) |

---

## 📝 NOTES

This registry is **auto-generated** by CIVIC and reflects the authoritative citizen registry.
When you add or modify an agent, CIVIC's `scan_and_register_agents()` method updates this document.

### How It Works

1. **Discovery**: Scans all `*/cartridge_main.py` files
2. **Extraction**: Parses class definitions and docstrings
3. **Validation**: Checks cartridge configurations
4. **Tools**: Discovers `*/tools/*.py` modules
5. **Generation**: Updates `AGENTS.md` via RegistryTool

This is **Layer 3 (Discovery)** of the Steward Protocol—the system explaining itself.

---

**CIVIC AUTHORITY NOTICE:**
This registry is maintained by The Bureaucrat. Any agent not listed here is not registered.
Unregistered agents cannot obtain broadcast licenses. No exceptions. 🏛️
"""

        return content

    def _format_agent_section(self, agent: Dict[str, Any]) -> str:
        """Format a single agent section."""
        section = f"""### 🤖 {agent['agent_name_pretty']}

**Class:** `{agent['class_name']}`
**Version:** `{agent['version']}`
**Status:** 🟢 OPERATIONAL

**Description:**
{agent['class_doc'] or "Autonomous agent in the Steward Protocol ecosystem."}

"""

        # Tools section
        if agent['tools']:
            section += "**Tools:**\n\n"
            for tool in agent['tools']:
                desc = f" — {tool['description']}" if tool['description'] else ""
                section += f"- **{tool['name']}** (`{tool['file']}`) {desc}\n"
        else:
            section += "**Tools:** None discovered\n"

        section += "\n"
        return section

    def render_to_file(self, output_file: str = "AGENTS.md") -> bool:
        """Render and write to file."""
        try:
            content = self.scan_and_render()
            output_path = self.root_dir / output_file

            output_path.write_text(content)
            print(f"✅ AGENTS.md generated: {output_path}")
            print(f"📊 Discovered {len(self.agents)} agents")
            print(f"🔧 Total tools: {sum(len(a['tools']) for a in self.agents.values())}")

            return True
        except Exception as e:
            print(f"❌ Error writing AGENTS.md: {e}")
            return False
