#!/usr/bin/env python3
"""
SCRIBE Help Renderer - Generate HELP.md

3-LAYER CONTROL CENTER:
1. THE PULSE - Background operations (CI/CD, Git)
2. CONTROL ROOM - Tunable parameters
3. DIAGNOSTICS - System health

Dynamic discovery, zero hardcoding.
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Any
from .introspector import CartridgeIntrospector, ScriptIntrospector, ConfigIntrospector
from .operations_introspector import WorkflowIntrospector, GitActivityIntrospector, ParameterIntrospector


class HelpRenderer:
    """Render HELP.md as 3-layer control center."""

    def __init__(self, root_dir: str = "."):
        self.root_dir = Path(root_dir)

        # Introspectors
        self.cart_introspector = CartridgeIntrospector(root_dir)
        self.script_introspector = ScriptIntrospector(root_dir)
        self.config_introspector = ConfigIntrospector(root_dir)

        # Operations introspectors
        self.workflow_introspector = WorkflowIntrospector(root_dir)
        self.git_introspector = GitActivityIntrospector(root_dir)
        self.param_introspector = ParameterIntrospector(root_dir)

    def scan_and_render(self) -> str:
        """Scan system and render HELP.md."""
        # Discover everything
        workflows = self.workflow_introspector.scan_all()
        git_activity = self.git_introspector.get_activity()
        params = self.param_introspector.scan_all_params()

        agents = self._load_agents_from_registry()
        entry_points = self.script_introspector.discover_entry_points()
        ledger_status = self._check_ledger_status()

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        content = f"""# 🎛️ SYSTEM CONTROL CENTER

**Auto-generated by SCRIBE (The Documentarian)**
**Last Updated:** {timestamp}
**Status:** 🟢 System Introspection Active

---

## 🚀 QUICK START

### 1️⃣ First Time? Start Here
```bash
# Initialize the system and create your ledger
python scripts/summon.py
```

### 2️⃣ Then, Explore the Agents
Read **[AGENTS.md](./AGENTS.md)** to see all registered agents in the system.

### 3️⃣ Understand the Complete Architecture
Check **[CITYMAP.md](./CITYMAP.md)** for the 3-layer city map (kernel, routing, agents).

### 4️⃣ Review the Constitution
All agents operate under **[CONSTITUTION.md](./CONSTITUTION.md)** rules.

---

## 🔄 LAYER 1: THE PULSE (Background Operations)

What's running in the background while you sleep?

### CI/CD Automations

{self._render_workflows(workflows)}

### Git Heartbeat

{self._render_git_activity(git_activity)}

---

## 🎛️ LAYER 2: CONTROL ROOM (Tunable Parameters)

The levers you can pull to control Agent City.

### 💰 Economic Settings

{self._render_economy_params(params.get('economy', dict()))}

### 🔒 Security Settings

{self._render_security_params(params.get('security', dict()))}

---

## 🚨 LAYER 3: DIAGNOSTICS (System Health)

Actionable intelligence - what's broken and how to fix it.

### System Health Check

{self._render_diagnostics(ledger_status, agents)}

### Agent Status

{self._render_agent_status(agents)}

---

## 📋 AVAILABLE SCRIPTS

How to interact with Agent City:

{self._render_entry_points(entry_points)}

---

## ⚙️ CORE OPERATIONS

### Starting the System
```bash
# Initialize and start
python scripts/summon.py
```

### Checking Status
```bash
# View current ledger and agent status
python scripts/verify_docs.py
```

### Viewing System
- See all agents: **[AGENTS.md](./AGENTS.md)**
- See 3-layer architecture: **[CITYMAP.md](./CITYMAP.md)** (kernel + routing + agents)

### Governance
- View constitution: **[CONSTITUTION.md](./CONSTITUTION.md)**
- Check governance: See "Proposals" section in **[CITYMAP.md](./CITYMAP.md)**

---

## 📚 DOCUMENTATION FILES

| File | Purpose |
|------|---------|
| **[README.md](./README.md)** | Project overview and purpose |
| **[CONSTITUTION.md](./CONSTITUTION.md)** | Immutable rules all agents follow |
| **[AGENTS.md](./AGENTS.md)** | Registry of all active agents (auto-generated) |
| **[CITYMAP.md](./CITYMAP.md)** | Complete 3-layer city map: kernel, routing, agents (auto-generated) |
| **[HELP.md](./HELP.md)** | This file — system control center (auto-generated) |

---

## 🛠️ DEVELOPMENT

### Adding a New Agent

1. Create a new directory: `mkdir myagent`
2. Create `myagent/cartridge_main.py` with your agent logic
3. Run `python civic/tools/registry_tool.py .` to register
4. Your agent appears in `AGENTS.md` automatically

### Updating Documentation

These docs are **auto-generated** from actual code:
- `AGENTS.md` — Updated by SCRIBE (agents_renderer.py)
- `CITYMAP.md` — Updated by SCRIBE (citymap_renderer.py with 3-layer introspection)
- `HELP.md` — Updated by SCRIBE (help_renderer.py with operations introspection)
- `README.md` — Updated by SCRIBE (readme_renderer.py)

To regenerate all docs:
```bash
python -m steward.system_agents.scribe.cartridge_main
```

---

## 🔍 SYSTEM ARCHITECTURE OVERVIEW

```
Agent City is a federated system with:

🏛️ CIVIC (Authority) — Registry, licenses, credits
🗳️ FORUM (Democracy) — Proposals and voting
🦅 HERALD (Media) — Publishing and broadcasting
+ Other specialized agents (see AGENTS.md)

All agents follow CONSTITUTION.md rules.
All transactions recorded in ledger (immutable).
```

See **[CITYMAP.md](./CITYMAP.md)** for full architecture.

---

## ❓ COMMON QUESTIONS

### Where do I start?
→ Run `python scripts/summon.py` then read **AGENTS.md**

### How do agents communicate?
→ See **CITYMAP.md** for dependency graph

### What are the rules?
→ Read **CONSTITUTION.md** (immutable law)

### Where is the data stored?
→ `.steward/ledger.json` (immutable ledger)

### How do I add my own agent?
→ See "Development" section above

### Why is documentation auto-generated?
→ Because code is the source of truth. Docs stay in sync.

---

## 📞 SUPPORT

**This help was auto-generated** from your actual system state.
If you see stale information, run:
```bash
python -m steward.system_agents.scribe.cartridge_main
```

For detailed information:
- Agent details → **[AGENTS.md](./AGENTS.md)**
- Complete architecture (3 layers) → **[CITYMAP.md](./CITYMAP.md)**
- Rules → **[CONSTITUTION.md](./CONSTITUTION.md)**
- Code → Check `*/cartridge_main.py` files

---

**Generated by:** scribe/tools/help_renderer.py
**Authority:** SCRIBE (The Documentarian)
**Philosophy:** "A system that knows itself is a system that controls itself."
"""

        return content

    def _render_workflows(self, workflows: List[Dict[str, Any]]) -> str:
        """Render CI/CD workflows."""
        if not workflows:
            return "⚠️  No GitHub Actions workflows discovered\n"

        output = "**Discovered Workflows:**\n\n"

        for workflow in workflows:
            output += f"**{workflow['name']}** (`{workflow['file']}`)\n"
            output += f"- **Triggers:** {', '.join(workflow['triggers'])}\n"
            if workflow.get('branches'):
                output += f"- **Branches:** {', '.join(workflow['branches'])}\n"
            output += "\n"

        output += "**Transparency:** You can see exactly when automation runs.\n"

        return output

    def _render_git_activity(self, git_activity: Dict[str, Any]) -> str:
        """Render Git activity."""
        last_commit = git_activity.get('last_commit', {})
        branch = git_activity.get('current_branch', 'unknown')
        status = git_activity.get('status', 'unknown')

        output = "**Current State:**\n\n"
        output += f"- **Branch:** `{branch}`\n"
        output += f"- **Status:** {status}\n"
        output += f"- **Last Commit:** `{last_commit.get('hash', 'unknown')}` - {last_commit.get('message', 'unknown')}\n"
        output += f"- **Author:** {last_commit.get('author', 'unknown')}\n"
        output += f"- **Time:** {last_commit.get('time', 'unknown')}\n"

        return output

    def _render_economy_params(self, economy: Dict[str, Any]) -> str:
        """Render economy parameters."""
        if not economy:
            return "⚠️  Economy parameters not discovered\n"

        output = "**Tunable Parameters:**\n\n"

        if 'starting_credits' in economy:
            output += f"- **Starting Credits:** {economy['starting_credits']} CR per agent\n"
            output += "  - *Change:* Edit `steward/system_agents/civic/tools/economy.py`\n\n"

        if 'api_cost' in economy:
            output += f"- **API Cost:** {economy['api_cost']} CR per call\n"
            output += "  - *Change:* Edit `steward/system_agents/civic/tools/economy.py`\n\n"

        output += "**Transparency:** See exactly what credits cost and where to change it.\n"

        return output

    def _render_security_params(self, security: Dict[str, Any]) -> str:
        """Render security parameters."""
        crimes = security.get('unforgivable_crimes', [])

        if not crimes:
            return "⚠️  Security parameters not discovered\n"

        output = "**Unforgivable Crimes (Instant Termination):**\n\n"

        for i, crime in enumerate(crimes, 1):
            output += f"{i}. `{crime}`\n"

        output += f"\n**Location:** `{security.get('location', 'unknown')}`\n"
        output += "\n**Transparency:** You know exactly what will get you killed.\n"

        return output

    def _render_diagnostics(self, ledger_status: Dict[str, Any], agents: List[str]) -> str:
        """Render diagnostics."""
        output = ""

        # Ledger check
        if not ledger_status.get("exists"):
            output += "🔴 **LEDGER NOT INITIALIZED**\n"
            output += "   → **Action:** Run `python scripts/summon.py`\n\n"
        else:
            output += "🟢 **Ledger:** Operational\n"
            if ledger_status.get('total_entries'):
                output += f"   → {ledger_status['total_entries']} entries recorded\n\n"

        # Agents check
        agent_count = len(agents) if agents else 0
        if agent_count > 0:
            output += f"🟢 **Agents:** {agent_count} registered\n\n"
        else:
            output += "🔴 **AGENTS NOT DISCOVERED**\n"
            output += "   → **Action:** Check system installation\n\n"

        return output

    def _render_agent_status(self, agents: List[str]) -> str:
        """Render agent status list."""
        if not agents:
            return "⚠️  No agents discovered\n"

        output = f"**Total:** {len(agents)} agents\n\n"

        for agent in agents:
            output += f"- **{agent}** ✅\n"

        return output

    def _render_entry_points(self, entry_points: List[Dict[str, str]]) -> str:
        """Render entry point scripts."""
        if not entry_points:
            return "No scripts found in `scripts/` directory.\n"

        output = ""

        for script in entry_points:
            desc = f" — {script['description']}" if script['description'] else ""
            output += f"### `{script['name']}`\n"
            output += f"**Location:** `{script['path']}`{desc}\n\n"
            output += f"**Usage:**\n```bash\npython {script['path']}\n```\n\n"

        return output

    def _load_agents_from_registry(self) -> List[str]:
        """Extract agent names from AGENTS.md."""
        return self.config_introspector.load_agents_from_registry()

    def _check_ledger_status(self) -> Dict[str, Any]:
        """Check if ledger exists."""
        ledger_file = self.root_dir / ".steward" / "ledger.json"

        if not ledger_file.exists():
            return {
                "exists": False,
                "message": "Ledger not yet initialized. Run `python scripts/summon.py` to start."
            }

        try:
            data = json.loads(ledger_file.read_text())
            entries = data.get("chain_of_trust", {}).get("entries", [])

            return {
                "exists": True,
                "total_entries": len(entries),
                "initialized": True,
                "last_update": entries[-1].get("timestamp", "unknown") if entries else "never"
            }
        except:
            return {"exists": True, "readable": False}

    def render_to_file(self, output_file: str = "HELP.md") -> bool:
        """Render and write to file."""
        try:
            content = self.scan_and_render()
            output_path = self.root_dir / output_file

            output_path.write_text(content)
            print(f"✅ HELP.md generated: {output_path}")

            return True
        except Exception as e:
            print(f"❌ Error writing HELP.md: {e}")
            return False
